version: '2.1'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: starterstack-mysql
    restart: always
    ports:
      - "24301:3306"
    volumes:
      - starterstack-datavolume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: starterstack
      MYSQL_USER: starterstack
      MYSQL_PASSWORD: your_secure_password
  nginx:
    container_name: starterstack-nginx
    build: ./nginx
    image: nginx:stable-alpine
    volumes:
        - ./app:/app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "80"
    labels:
      - "traefik.frontend.rule=Host:starterstack.local"
      - "traefik.port=80"
  php:
    build: .
    container_name: starterstack-php
    environment:
      DB_NAME: starterstack
      DB_USER: starterstack
      DB_PASSWORD: your_secure_password
      DB_HOST: starterstack-mysql
      WP_SITEURL: "https://starterstack.local"
      WP_DEBUG: "true"
    volumes:
        - ./app:/app
    ports:
        - "9000:9000"

volumes:
  starterstack-datavolume:

networks:
  default:
    external:
      name: traefik_hosts