services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    restart: always
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # No manual naming needed, auto-prefixed by COMPOSE_PROJECT_NAME
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}
      MYSQL_USER: ${COMPOSE_PROJECT_NAME}
      MYSQL_PASSWORD: your_secure_password

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    image: nginx:alpine
    volumes:
      - ./app:/app
      - ./nginx/templates:/etc/nginx/templates:rw,cached
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "80"
    labels:
      - "traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.my.local"
      - "traefik.port=80"

  php:
    build: .
    container_name: ${COMPOSE_PROJECT_NAME}-php
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      DB_NAME: ${COMPOSE_PROJECT_NAME}
      DB_USER: ${COMPOSE_PROJECT_NAME}
      DB_PASSWORD: your_secure_password
      DB_HOST: ${COMPOSE_PROJECT_NAME}-mysql
      WP_SITEDOMAIN: "${COMPOSE_PROJECT_NAME}.my.local"
      WP_SITEURL: "https://${COMPOSE_PROJECT_NAME}.my.local"
      WP_DEBUG: "1"
      WP_DEBUG_DISPLAY: "1"
      WP_DEBUG_LOG: "1"
    volumes:
      - ./app:/app
    ports:
      - "${PHP_PORT:-9000}:9000"

volumes:
  mysql_data:  # This will be automatically prefixed by COMPOSE_PROJECT_NAME

networks:
  default:
    name: traefik_hosts
    external: true
